### ISSUE TITLE
EPICS 7 packaging

### ISSUE THREAD

**Issue by daykin** [epicsdeb/epics-base#28]
Hi everyone,

Is there any documentation surrounding efforts to get EPICS 7.0.x packaged? IIRC it isn't so simple, but if someone is familiar, could I get a short briefing on any roadblocks stopping this from happening?

**Comment by mark0n** [comment]
Nothing has been done/documented, yet. Shouldn't be too difficult but since the directory tree and the way the files need to be split up into packages has changed significantly, I would expect that it will take even someone who's familiar with EPICS 7 a few days to get all the details right. Unfortunately, I never managed to convince management that this needed to be done so it never happened. I'm not aware of any roadblocks, though.

**Comment by chrschroeder** [comment]
Hello Evan. We are still using EPICS Debian packages to some extent. It's appreciated that you adopted some of the repositories. Two points:
1. Is it possible to merge Martins last pull-requests? I think they are tested as good as possible with the few users left. We are using them with 3.15.9 imported on top.
2. Since you did some work to debianize EPICS 7, are you aware that EPICS packages are part of Debian Testing / sid or is that maybe done by you? See: https://packages.debian.org/source/trixie/epics-base It's great to see EPICS in the official Debian repository and maybe this can be used as base dependency to build other packages from epicsdeb against it.

**Comment by daykin** [comment]
Hi Christoph,

>Is it possible to merge Martins last pull-requests? I think they are tested as good as possible with the few users left. We are using them with 3.15.9 imported on top

Seeing as NSLSII has moved away from Debian, as far as I know, it's a one man show. I have no problem merging it. On top of that, we have since packaged 7.0.8.1 which we are using in production at FRIB. 

>Since you did some work to debianize EPICS 7, are you aware that EPICS packages are part of Debian Testing / sid or is that maybe done by you?

That is a surprise to be sure, but a welcome one.  Haven't looked at what the differences are, if any.  For the moment, I'll continue to maintain this one in parallel. The only big modification on our end is eliminating a couple of tests using the loopback interface, since our CI infrastructure can't deal with it.

**Comment by daykin** [comment]
@chrschroeder  
#32 #33 #34 are our current production branch, which we've been using for some months with no issues. If you have a moment, see if you can build it from scratch on your end.

**Comment by chrschroeder** [comment]
@daykin Sorry for the late reply. I currently can't spend much time on the debianization topic, but it will be more urgent next year when Debian 13 arrives. I tried to build the packages with your changes for Debian 11. The build got really far, but failed on dh_installman.
```
   dh_installman -O-Sepicsmake
dh_installman: error: Cannot find (any matches for) "debian/man/softIoc.1" (tried in .)
...
dh_installman: error: Aborting due to earlier error
make: *** [debian/rules:50: binary] Error 25
```
Maybe the filename is wrong? I have a softioc.1 file in the man directory.
```
root@fern:/tmp/buildd/epics-base-7.0.8.1# ls -l debian/man/softIoc.1
ls: cannot access 'debian/man/softIoc.1': No such file or directory
root@fern:/tmp/buildd/epics-base-7.0.8.1# ls -l debian/man/soft*
-rw-r--r-- 1 pbuilder pbuilder 19 Nov 12 17:01 debian/man/softioc.1
-rw-r--r-- 1 pbuilder pbuilder 22 Nov 12 17:01 debian/man/softiocpva.1
```

For Debian 13 and onwards we should consider to build against the new base packages. Otherwise it will be difficult because of namespace collision. There are  EPICS 7 packages available in Ubuntu 24.04. I guess they are based on the same Debian packages. They look good, but there are minor issues for example developer tools like softIoc and softIocPVA are missing in their epics-dev package.

**Comment by daykin** [comment]
Hi Christoph,

Sorry about the delay. 
Regarding the softIoc man page issue, I think I inelegantly copied everything to a windows machine at some point, which would cause the file paths to become case-insensitive. This is fixed now on the repo. I have also fixed the config file name issue. Thank you for pointing these out!

If you have a moment, try building this branch from scratch once more. If there aren't issues, I will merge it then.

I think when our facility updates to Debian Trixie, we will retire this one and use the one maintained by Debian Science Team if there aren't any issues with it.

**Comment by chrschroeder** [comment]
@daykin Hi Evan,

I pulled your new pullrequest and now the build runs without any issues. Thanks again!
